version: "3.9"

services:
  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - ./redis-volume:/data

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb:
